// ================= v20 · 📏 CelebriR8 · LOS REPUESTOS DEL PRECISION LAB =================
// Cada repuesto dice qué MEDIDAS necesita, cuáles son imprescindibles (si faltan, se piden: nunca se inventan), cuáles
// llevan un valor ESTIMADO de partida (el ángulo de presión «más común», el juego para impresión…) que hay que confirmar,
// y cuáles se CALCULAN (con su fórmula). Con las medidas se construye la pieza con geometría de CAD (Manifold), se
// comprueba si algo no casa y se prepara su PRUEBA DE ENCAJE pequeña («no me hagas nada que luego no encaje»).
import * as N from './nucleo.js';
import * as G from './engranajes.js';
import { ENCAJES } from './motor.js';
import { diferencial, RODAMIENTOS, TORNILLOS } from './diferencial.js';

const n = (k, t, o = {}) => Object.assign({ k, t, tipo: 'num', u: 'mm', paso: 0.01, min: 0 }, o);
const s = (k, t, ops, o = {}) => Object.assign({ k, t, tipo: 'sel', ops }, o);
const c = (k, t, o = {}) => Object.assign({ k, t, tipo: 'chk' }, o);
const tx = (k, t, o = {}) => Object.assign({ k, t, tipo: 'txt' }, o);
const f = (x, d = 2) => G.fmt(x, d);

// ---------- campos comunes de engranaje ----------
const POR = s('por', 'Tamaño del diente por', [['modulo', 'Módulo (mm)'], ['dp', 'Paso diametral (DP, en pulgadas)'], ['diametro', 'Diámetro primitivo']], { def: 'modulo', ayuda: 'Los engranajes métricos se miden por MÓDULO; los americanos o ingleses por PASO DIAMETRAL (dientes por pulgada de diámetro). Si solo sabes el diámetro primitivo, pon ese.' });
const TAM = [
  n('m', 'Módulo', { req: 1, min: 0.2, max: 20, paso: 0.05, si: v => v.por === 'modulo', ayuda: 'Se mide así: diámetro exterior ÷ (dientes + 2). Ejemplo: 33 mm con 20 dientes → 33 ÷ 22 = 1,5. Normalizados: 0,5 · 0,8 · 1 · 1,25 · 1,5 · 2 · 2,5 · 3.' }),
  n('dp', 'Paso diametral (DP)', { req: 1, u: '', min: 1, max: 200, paso: 1, si: v => v.por === 'dp', ayuda: 'Dientes por pulgada de diámetro. Se mide: (dientes + 2) ÷ diámetro exterior en pulgadas. Habituales: 48 · 32 · 24 · 20 · 16 · 12 · 10.' }),
  n('d', 'Diámetro primitivo', { req: 1, min: 2, max: 1000, si: v => v.por === 'diametro', ayuda: 'El diámetro de la circunferencia donde engranan (no el de fuera). Si solo tienes el de fuera, usa «Módulo»: módulo = exterior ÷ (dientes + 2).' })];
const ALFA = s('alfa', 'Ángulo de presión', [['20', '20° (el más común)'], ['14.5', '14,5° (antiguos, americanos)'], ['25', '25° (refuerzos, algunos RC)']], { def: '20', est: 1, ayuda: 'Tiene que ser IGUAL al del engranaje con el que engrana. Si no lo sabes, 20° es lo más habitual en métrico; los muy antiguos o en pulgadas pueden ser 14,5°.' });
const HELICE = [
  s('forma', 'Dientes', [['recto', 'Rectos'], ['helicoidal', 'Helicoidales (inclinados)'], ['espiga', 'En espiga (doble hélice)']], { def: 'recto' }),
  n('beta', 'Ángulo de hélice', { req: 1, u: '°', min: 1, max: 45, paso: 0.5, si: v => v.forma !== 'recto', ayuda: 'Lo inclinado que va el diente respecto al eje. Lo normal: 10° a 30°. Se mide con un transportador sobre el canto, o con la huella del diente en un papel.' }),
  s('mano', 'Mano de la hélice', [['der', 'A derechas (como un tornillo normal)'], ['izq', 'A izquierdas']], { def: 'der', est: 1, si: v => v.forma !== 'recto', ayuda: 'Mírala de canto: si los dientes suben hacia la DERECHA, como la rosca de un tornillo normal, es a derechas. Dos engranajes por fuera llevan manos contrarias.' })];
const EJE = (suf = '', titulo = 'Agujero del eje') => [
  n('eje' + suf, titulo, { req: 1, min: 0, max: 200, ayuda: 'El diámetro del eje donde va (mídelo con el calibre en el EJE, no en el agujero gastado). 0 = sin agujero.' }),
  s('ejeForma' + suf, 'Forma del agujero', [['redondo', 'Redondo'], ['d', 'En D (con plano)'], ['hex', 'Hexagonal (mide entre caras)']], { def: 'redondo' }),
  n('plano' + suf, 'Del plano al otro lado', { req: 1, min: 0.5, max: 200, si: v => v['ejeForma' + suf] === 'd', ayuda: 'En un eje en D: la medida desde la cara plana hasta el lado redondo de enfrente.' })];
const HOLGURA = s('holgura', 'Ajuste en el eje', [['presion', 'A presión · ' + f(ENCAJES.presion) + ' por lado'], ['justo', 'Encaja · ' + f(ENCAJES.justo)], ['gira', 'Gira libre · ' + f(ENCAJES.gira)]], { def: 'presion', est: 1, ayuda: 'Son TUS holguras medidas en tus Bambu. La prueba de encaje lo confirma.' });
const JUEGO = n('juego', 'Juego entre dientes', { def: 0.1, est: 1, min: 0, max: 0.6, paso: 0.01, ayuda: 'Lo que se quita a cada diente para que no se atasque al imprimirlo. Para empezar 0,10 mm; la prueba de engrane dice si sobra o falta.' });
const XSH = n('x', 'Desplazamiento de perfil', { def: 0, est: 1, u: '× m', min: -0.5, max: 1, paso: 0.05, ayuda: 'Casi siempre 0. Se usa para piñones de pocos dientes (para que no se socaven) o para ajustar la distancia entre ejes. Si el original lo lleva, solo lo sabrás por su ficha.' });
const BUJE = [c('buje', 'Con buje (refuerzo alrededor del eje)', { def: false }), n('bujeD', 'Diámetro del buje', { req: 1, min: 2, max: 300, si: v => v.buje }), n('bujeH', 'Alto del buje', { req: 1, min: 0.5, max: 100, si: v => v.buje })];
const hol = v => ENCAJES[v.holgura] ?? ENCAJES.presion;
const gearP = (v, suf = '') => ({ por: v.por, m: v.m, dp: v.dp, d: v.d, z: v['z' + suf], alfa: Number(v.alfa), beta: v.forma === 'recto' ? 0 : v.beta, mano: v['mano' + suf] || v.mano, tipo: v.forma === 'espiga' ? 'espiga' : v.forma === 'helicoidal' ? 'helicoidal' : 'recto', x: v['x' + suf] || 0, juego: v.juego || 0, b: v.b, eje: v['eje' + suf], ejeForma: v['ejeForma' + suf], plano: v['plano' + suf], holgura: hol(v), buje: v.buje, bujeD: v.bujeD, bujeH: v.bujeH });
const otraMano = m => m === 'izq' ? 'der' : 'izq';
const DATOS = [tx('pieza', 'Qué pieza es', { ayuda: 'Por ejemplo: «engranaje del motor de la batidora».' }), tx('marca', 'Marca del aparato'), tx('modelo', 'Modelo del aparato'), tx('notas', 'Notas (dónde va, cuánto se gastó…)')];

// ---------- los repuestos ----------
export const TIPOS = {
  engranaje: { e: '⚙️', t: 'Engranaje', d: 'Recto, helicoidal o en espiga',
    campos: [POR, ...TAM, n('z', 'Número de dientes', { req: 1, u: '', min: 6, max: 400, paso: 1, ayuda: 'Cuéntalos marcando uno con rotulador.' }), ALFA, ...HELICE, n('b', 'Ancho (grosor) del diente', { req: 1, min: 1, max: 200 }), ...EJE(), HOLGURA, JUEGO, XSH, ...BUJE],
    ejemplo: { por: 'modulo', m: 1.5, z: 20, b: 8, eje: 5 },
    calcula(v) { const K = G.numeros(gearP(v)); return [['Módulo', f(K.mn, 4), K.mn ? (v.por === 'dp' ? '25,4 ÷ DP' : v.por === 'diametro' ? 'diámetro primitivo × cos β ÷ dientes' : 'el que has puesto') : ''], ['Paso diametral equivalente', f(K.dp, 3), '25,4 ÷ módulo'], ['Diámetro primitivo', f(K.d, 3) + ' mm', 'módulo transversal × dientes'], ['Diámetro exterior (punta)', f(2 * K.ra, 3) + ' mm', 'primitivo + 2 × módulo × (1 + x)'], ['Diámetro de fondo', f(2 * K.rf, 3) + ' mm', 'primitivo − 2 × 1,25 × módulo'], ['Diámetro base', f(2 * K.rb, 3) + ' mm', 'primitivo × cos(ángulo de presión)'], ['Paso circular', f(K.paso, 3) + ' mm', 'π × módulo'], ['Espesor del diente', f(K.s, 3) + ' mm', 'en el primitivo, ya con el juego'], v.forma !== 'recto' ? ['Giro del diente en el ancho', f(K.torsion, 2) + '°', 'ancho × tan β ÷ radio primitivo'] : null].filter(Boolean); },
    revisa: v => G.revisaPieza(gearP(v)),
    construye(v) { return { partes: [{ m: G.engranaje(gearP(v)).m, nombre: 'engranaje' }] }; },
    cotas(v) { const K = G.numeros(gearP(v)); return [{ a: [-K.ra, -K.ra - 4, v.b], b: [K.ra, -K.ra - 4, v.b], t: 'Ø ' + f(2 * K.ra, 2) + ' (punta)' }, { a: [K.ra + 4, 0, 0], b: [K.ra + 4, 0, v.b], t: f(v.b, 2) }, v.eje > 0 ? { a: [-v.eje / 2, 0, v.b + (v.buje ? v.bujeH : 0) + 1], b: [v.eje / 2, 0, v.b + (v.buje ? v.bujeH : 0) + 1], t: 'Ø ' + f(v.eje, 2) } : null].filter(Boolean); },
    kit(v) { return { t: 'Prueba de engrane: el mismo engranaje con 3 mm de ancho', d: 'Prueba que entra en el eje y que engrana con la pieza original del aparato antes de imprimir el de ' + f(v.b, 1) + ' mm.', partes: [{ m: G.engranaje(Object.assign(gearP(v), { b: Math.min(3, v.b), buje: false })).m, nombre: 'prueba_engrane' }] }; } },

  par: { e: '⚙️⚙️', t: 'Pareja de engranajes', d: 'Dos que engranan + distancia entre ejes',
    campos: [s('por', 'Tamaño del diente por', [['modulo', 'Módulo (mm)'], ['dp', 'Paso diametral (DP)']], { def: 'modulo' }), TAM[0], TAM[1], n('z1', 'Dientes del piñón (el pequeño)', { req: 1, u: '', min: 6, max: 400, paso: 1 }), n('z2', 'Dientes de la rueda (el grande)', { req: 1, u: '', min: 6, max: 400, paso: 1 }), ALFA, HELICE[0], HELICE[1], s('mano1', 'Mano de la hélice del piñón', [['der', 'A derechas'], ['izq', 'A izquierdas']], { def: 'der', est: 1, si: v => v.forma !== 'recto', ayuda: 'La rueda llevará la contraria (lo hace el programa).' }),
      n('b', 'Ancho del diente', { req: 1, min: 1, max: 200 }), ...EJE('1', 'Eje del piñón'), ...EJE('2', 'Eje de la rueda'), HOLGURA, JUEGO, n('aReal', 'Distancia entre ejes de tu aparato (si la sabes)', { min: 0, max: 2000, ayuda: 'Mídela de centro a centro de los ejes. Si la pones, compruebo que estos engranajes caben ahí. 0 = no la sé.' })],
    ejemplo: { por: 'modulo', m: 1.5, z1: 20, z2: 40, b: 8, eje1: 5, eje2: 6 },
    pares(v) { return [Object.assign(gearP(v, '1'), { mano: v.mano1 || 'der' }), Object.assign(gearP(v, '2'), { mano: otraMano(v.mano1 || 'der') })]; },
    calcula(v) { const [A, B] = this.pares(v), C = G.casan(A, B, 'exterior'), KA = G.numeros(A), KB = G.numeros(B); return [['Distancia entre ejes', f(C.a, 3) + ' mm', '(primitivo 1 + primitivo 2) ÷ 2'], ['Relación', '1 : ' + f(C.i, 3), 'dientes rueda ÷ dientes piñón'], ['Relación de contacto', f(C.eps, 3), 'dientes apoyando a la vez (más de 1,2)'], ['Ø exterior piñón · rueda', f(2 * KA.ra, 2) + ' · ' + f(2 * KB.ra, 2) + ' mm', ''], v.forma !== 'recto' ? ['Manos', (A.mano === 'der' ? 'derechas' : 'izquierdas') + ' · ' + (B.mano === 'der' ? 'derechas' : 'izquierdas'), 'contrarias (por fuera)'] : null].filter(Boolean); },
    revisa(v) { const [A, B] = this.pares(v), C = G.casan(A, B, 'exterior'), L = C.avisos.concat(G.revisaPieza(A).filter(x => x.n !== 'ok').map(x => Object.assign({}, x, { t: 'Piñón: ' + x.t })), G.revisaPieza(B).filter(x => x.n !== 'ok').map(x => Object.assign({}, x, { t: 'Rueda: ' + x.t })));
      if (v.aReal > 0) { const dif = C.a - v.aReal; if (Math.abs(dif) > 0.05) { const be = (A.beta || 0) * G.RAD, mt = G.numeros(A).mt, zs = 2 * v.aReal / mt, at = G.numeros(A).at, a0 = mt * (A.z + B.z) / 2, cw = a0 * Math.cos(at) / v.aReal; let xs = null; if (cw < 1 && cw > 0.5) { const aw = Math.acos(cw); xs = ((Math.tan(aw) - aw) - (Math.tan(at) - at)) * (A.z + B.z) / (2 * Math.tan(Number(v.alfa) * G.RAD)); }
        L.unshift({ n: 'error', t: 'NO CABEN EN TU APARATO: con estos dientes y este módulo los ejes quedan a ' + f(C.a, 3) + ' mm, y en tu aparato están a ' + f(v.aReal, 3) + ' mm (' + (dif > 0 ? 'sobran ' : 'faltan ') + f(Math.abs(dif), 2) + ' mm). Con módulo ' + f(G.moduloDe(A), 3) + ' necesitarías ' + f(zs, 2) + ' dientes entre los dos' + (Math.abs(zs - Math.round(zs)) < 0.02 ? ' (prueba ' + Math.round(zs) + ')' : ' (no sale entero') + (xs != null && Math.abs(zs - Math.round(zs)) >= 0.02 ? ': o desplazamiento de perfil total x₁ + x₂ = ' + f(xs, 3) + ')' : Math.abs(zs - Math.round(zs)) >= 0.02 ? ')' : '') + '. Revisa también el módulo: ¿es otro, o va en DP?' }); } else L.unshift({ n: 'ok', t: 'Caben en tu aparato: ' + f(C.a, 3) + ' mm entre ejes (has medido ' + f(v.aReal, 2) + ').' }); }
      return L; },
    construye(v) { const [A, B] = this.pares(v), C = G.casan(A, B, 'exterior'), ga = G.engranaje(A).m, gb = G.engranaje(B).m.rotate([0, 0, B.z % 2 === 0 ? 180 / B.z : 0]).translate([C.a, 0, 0]); return { partes: [{ m: ga, nombre: 'pinon_' + A.z, color: '#2457d6' }, { m: gb, nombre: 'rueda_' + B.z, color: '#ff8a3d' }], montaje: { a: ga, b: gb, que: 'los dos engranajes a su distancia entre ejes' } }; },
    cotas(v) { const [A, B] = this.pares(v), C = G.casan(A, B, 'exterior'); return [{ a: [0, -G.numeros(B).ra - 6, 0], b: [C.a, -G.numeros(B).ra - 6, 0], t: f(C.a, 3) + ' entre ejes' }]; },
    kit(v) { const [A, B] = this.pares(v), C = G.casan(A, B, 'exterior'), fino = o => Object.assign({}, o, { b: Math.min(3, v.b), buje: false }), pin = d => d > 0 ? d - 2 * ENCAJES.gira : 0, KB = G.numeros(B), KA = G.numeros(A);
      const L = C.a + KA.ra + KB.ra + 10, W = 2 * Math.max(KA.ra, KB.ra) + 6, base = N.forma3d('caja', { x: L, y: Math.max(14, W * 0.35), z: 2, radio: 3 }).translate([C.a / 2 + (KB.ra - KA.ra) / 2, 0, 0]);
      const pina = pin(v.eje1) > 0 ? N.forma3d('cilindro', { d: pin(v.eje1), h: 2 + 5 }) : null, pinb = pin(v.eje2) > 0 ? N.forma3d('cilindro', { d: pin(v.eje2), h: 2 + 5 }).translate([C.a, 0, 0]) : null;
      return { t: 'Prueba de engrane: base con dos ejes a ' + f(C.a, 2) + ' mm + los dos engranajes con 3 mm de ancho', d: 'Los ejes de prueba miden tu eje menos tu holgura «gira»: los engranajes deben girar suaves, sin atascarse ni bailar. Si se atascan, sube el juego 0,05; si bailan, bájalo.', partes: [{ m: fino(A) && G.engranaje(fino(A)).m.translate([0, W, 0]), nombre: 'pinon_prueba' }, { m: G.engranaje(fino(B)).m.translate([C.a, W + KB.ra + KA.ra, 0]), nombre: 'rueda_prueba' }, { m: N.union([base, pina, pinb].filter(Boolean)).translate([0, -W, 0]), nombre: 'base_ejes' }] }; } },

  cremallera: { e: '📏', t: 'Cremallera', d: 'Barra dentada recta o helicoidal',
    campos: [s('por', 'Tamaño del diente por', [['modulo', 'Módulo (mm)'], ['dp', 'Paso diametral (DP)']], { def: 'modulo' }), TAM[0], TAM[1], ALFA, s('forma', 'Dientes', [['recto', 'Rectos'], ['helicoidal', 'Inclinados (helicoidal)']], { def: 'recto' }), HELICE[1], HELICE[2], n('nd', 'Número de dientes', { req: 1, u: '', min: 1, max: 400, paso: 1, ayuda: 'O mide el largo y divídelo por el paso (π × módulo).' }), n('b', 'Ancho del diente', { req: 1, min: 1, max: 200 }), n('fondo', 'Grosor bajo los dientes', { req: 1, min: 0.8, max: 100, ayuda: 'Lo que mide la barra por debajo del fondo de los dientes.' }), JUEGO],
    ejemplo: { por: 'modulo', m: 1.5, nd: 12, b: 8, fondo: 4 },
    p(v) { return { por: v.por, m: v.m, dp: v.dp, alfa: Number(v.alfa), beta: v.forma === 'recto' ? 0 : v.beta, mano: v.mano, n: v.nd, b: v.b, fondo: v.fondo, juego: v.juego || 0 }; },
    calcula(v) { const r = G.cremallera(this.p(v)); N.limpia(); const K = r.K; return [['Paso', f(K.paso, 3) + ' mm', 'π × módulo' + (K.be ? ' ÷ cos β' : '')], ['Largo', f(K.L, 2) + ' mm', 'dientes × paso'], ['Alto total', f(r.alto, 2) + ' mm', 'módulo + 1,25 × módulo + grosor bajo los dientes'], ['De la base a la línea primitiva', f(r.alto - K.ha, 2) + ' mm', 'donde engrana con el piñón'], ['Avance por vuelta de un piñón de z dientes', 'z × ' + f(K.paso, 3) + ' mm', '']]; },
    revisa(v) { const L = G.revisaPieza(Object.assign(this.p(v), { z: 40 })).filter(x => !/dientes|SOCAVADO|agujero/.test(x.t)); return L.length ? L : [{ n: 'ok', t: 'Sin problemas en la geometría.' }]; },
    construye(v) { return { partes: [{ m: G.cremallera(this.p(v)).m, nombre: 'cremallera' }] }; },
    cotas(v) { const r = G.cremallera(this.p(v)); N.limpia(); return [{ a: [-r.K.L / 2, -r.alto + r.K.ha - 4, 0], b: [r.K.L / 2, -r.alto + r.K.ha - 4, 0], t: f(r.K.L, 2) + ' de largo' }]; },
    kit(v) { return { t: 'Prueba: 4 dientes de la misma cremallera', d: 'Compárala con la original o pruébala con su piñón antes de imprimir la barra entera.', partes: [{ m: G.cremallera(Object.assign(this.p(v), { n: Math.min(4, v.nd), b: Math.min(4, v.b) })).m, nombre: 'cremallera_prueba' }] }; } },

  pinonCremallera: { e: '⚙️📏', t: 'Piñón + cremallera', d: 'Giro → recorrido en línea recta',
    campos: [s('por', 'Tamaño del diente por', [['modulo', 'Módulo (mm)'], ['dp', 'Paso diametral (DP)']], { def: 'modulo' }), TAM[0], TAM[1], ALFA, n('z1', 'Dientes del piñón', { req: 1, u: '', min: 8, max: 200, paso: 1 }), ...EJE('1', 'Eje del piñón'), n('nd', 'Dientes de la cremallera', { req: 1, u: '', min: 2, max: 400, paso: 1 }), n('b', 'Ancho del diente', { req: 1, min: 1, max: 200 }), n('fondo', 'Grosor bajo los dientes', { req: 1, min: 0.8, max: 100 }), HOLGURA, JUEGO],
    ejemplo: { por: 'modulo', m: 1.5, z1: 20, eje1: 5, nd: 16, b: 8, fondo: 4 },
    pp(v) { const A = Object.assign(gearP(v, '1'), { beta: 0, tipo: 'recto' }), R = { por: v.por, m: v.m, dp: v.dp, alfa: Number(v.alfa), beta: 0, n: v.nd, b: v.b, fondo: v.fondo, juego: v.juego || 0 }; return [A, R]; },
    calcula(v) { const [A, R] = this.pp(v), C = G.casan(A, R, 'cremallera'), K = G.numeros(A); return [['Del eje del piñón a la línea primitiva', f(C.a, 3) + ' mm', 'radio primitivo del piñón'], ['Avance por vuelta', f(Math.PI * K.d, 2) + ' mm', 'π × diámetro primitivo'], ['Relación de contacto', f(C.eps, 3), '']]; },
    revisa(v) { const [A, R] = this.pp(v); return G.casan(A, R, 'cremallera').avisos.concat(G.revisaPieza(A).filter(x => x.n !== 'ok')); },
    construye(v) { const [A, R] = this.pp(v), C = G.casan(A, R, 'cremallera'), K = G.numeros(A), cr = G.cremallera(R), desp = Math.round(R.n) % 2 === 1 ? cr.K.paso / 2 : 0;
      const pin = G.engranaje(A).m.rotate([0, 0, -90]).translate([0, C.a, 0]), bar = cr.m.translate([desp, 0, 0]); return { partes: [{ m: pin, nombre: 'pinon_' + A.z, color: '#2457d6' }, { m: bar, nombre: 'cremallera_' + R.n, color: '#ff8a3d' }], montaje: { a: pin, b: bar, que: 'el piñón apoyado en la cremallera' } }; },
    cotas(v) { const [A, R] = this.pp(v), C = G.casan(A, R, 'cremallera'); return [{ a: [G.numeros(A).ra + 6, 0, 0], b: [G.numeros(A).ra + 6, C.a, 0], t: f(C.a, 3) + ' del eje a la línea primitiva' }]; },
    kit(v) { const [A, R] = this.pp(v); return { t: 'Prueba: piñón de 3 mm + 5 dientes de cremallera', d: 'Comprueba que el piñón rueda sobre la cremallera sin saltar.', partes: [{ m: G.engranaje(Object.assign({}, A, { b: Math.min(3, v.b), buje: false })).m.translate([0, 30, 0]), nombre: 'pinon_prueba' }, { m: G.cremallera(Object.assign({}, R, { n: Math.min(5, R.n), b: Math.min(4, v.b) })).m, nombre: 'cremallera_prueba' }] }; } },

  corona: { e: '⭕', t: 'Corona interior', d: 'Aro con los dientes por dentro',
    campos: [POR, ...TAM, n('z', 'Dientes de la corona', { req: 1, u: '', min: 20, max: 400, paso: 1 }), ALFA, ...HELICE, n('b', 'Ancho del diente', { req: 1, min: 1, max: 200 }), n('Dext', 'Diámetro exterior del aro', { req: 1, min: 5, max: 2000, ayuda: 'Por fuera, con el calibre. Tiene que ser mayor que el fondo de los dientes + 2 × 1,6 mm.' }), n('zp', 'Dientes del piñón que va dentro (si lo sabes)', { u: '', min: 0, max: 400, paso: 1, ayuda: 'Para comprobar que no chocan las puntas y calcular la distancia entre ejes. 0 = no lo sé.' }), JUEGO, XSH],
    ejemplo: { por: 'modulo', m: 1.5, z: 60, b: 8, Dext: 104, zp: 20 },
    p(v) { const P = gearP(v); const K = G.numeros(P), rRaiz = K.r + 1.25 * K.mn; return Object.assign(P, { aro: v.Dext / 2 - rRaiz }); },
    calcula(v) { const P = this.p(v), K = G.numeros(P), L = [['Diámetro primitivo', f(K.d, 3) + ' mm', 'módulo × dientes'], ['Diámetro de las puntas (por dentro)', f(K.d - 2 * K.mn, 3) + ' mm', 'primitivo − 2 × módulo'], ['Diámetro del fondo (por dentro)', f(K.d + 2.5 * K.mn, 3) + ' mm', 'primitivo + 2,5 × módulo'], ['Grosor del aro', f(P.aro, 2) + ' mm', 'exterior ÷ 2 − radio del fondo']];
      if (v.zp > 0) { const C = G.casan(Object.assign({}, P, { z: v.zp, mano: P.mano }), P, 'interior'); L.push(['Distancia entre ejes con el piñón', f(C.a, 3) + ' mm', '(primitivo corona − primitivo piñón) ÷ 2'], ['Relación de contacto', f(C.eps, 3), '']); } return L; },
    revisa(v) { const P = this.p(v), L = []; if (P.aro < 1.6) L.push({ n: 'error', t: 'El diámetro exterior (' + f(v.Dext, 2) + ') no deja aro: hace falta al menos ' + f(2 * (G.numeros(P).r + 1.25 * G.numeros(P).mn + 1.6), 2) + ' mm.' }); if (v.zp > 0) L.push(...G.casan(Object.assign({}, P, { z: v.zp }), P, 'interior').avisos); L.push(...G.revisaPieza(Object.assign({}, P, { eje: 0 })).filter(x => x.n !== 'ok' && !/SOCAVADO/.test(x.t))); return L.length ? L : [{ n: 'ok', t: 'Sin problemas en la geometría.' }]; },
    construye(v) { const P = this.p(v), co = G.corona(P).m; if (v.zp > 0) { const C = G.casan(Object.assign({}, P, { z: v.zp }), P, 'interior'), pin = G.engranaje(Object.assign({}, P, { z: v.zp, eje: 0, buje: false })).m.translate([C.a, 0, 0]); return { partes: [{ m: co, nombre: 'corona_' + P.z, color: '#2457d6' }], fantasma: [{ m: pin, nombre: 'piñón (solo para ver)', color: '#ff8a3d' }], montaje: { a: co, b: pin, que: 'la corona con un piñón de ' + v.zp + ' dientes dentro' } }; } return { partes: [{ m: co, nombre: 'corona_' + P.z }] }; },
    cotas(v) { return [{ a: [-v.Dext / 2, -v.Dext / 2 - 5, v.b], b: [v.Dext / 2, -v.Dext / 2 - 5, v.b], t: 'Ø ' + f(v.Dext, 2) }]; },
    kit(v) { const P = this.p(v); return { t: 'Prueba: un cuarto de la corona con 3 mm de ancho', d: 'Para comprobar el engrane con el piñón y la curva del aro antes de imprimirla entera.', partes: [{ m: G.corona(Object.assign({}, P, { b: Math.min(3, v.b) })).m.intersect(N.forma3d('caja', { x: v.Dext / 2 + 2, y: v.Dext / 2 + 2, z: 10, radio: 0 }).translate([v.Dext / 4, v.Dext / 4, -1])), nombre: 'corona_prueba' }] }; } },

  casquillo: { e: '🔩', t: 'Casquillo / separador', d: 'Tubo corto para un eje',
    campos: [n('D', 'Diámetro exterior', { req: 1, min: 1, max: 500 }), n('di', 'Diámetro interior (el del eje)', { req: 1, min: 0, max: 500, ayuda: 'Mide el EJE. El agujero se hará con tu holgura.' }), n('L', 'Largo', { req: 1, min: 0.4, max: 500 }), HOLGURA, c('valona', 'Con valona (pestaña)', { def: false }), n('Dv', 'Diámetro de la valona', { req: 1, min: 1, max: 600, si: v => v.valona }), n('ev', 'Grosor de la valona', { req: 1, min: 0.4, max: 50, si: v => v.valona }), n('chaflan', 'Chaflán en los bordes', { def: 0.3, est: 1, min: 0, max: 5, ayuda: 'Un pequeño bisel para que entre fácil. 0 = sin chaflán.' })],
    ejemplo: { D: 22, di: 8, L: 10 },
    calcula(v) { const d = v.di + 2 * hol(v); return [['Agujero que se imprime', f(d, 3) + ' mm', 'eje + 2 × tu holgura'], ['Pared', f((v.D - d) / 2, 3) + ' mm', '(exterior − agujero) ÷ 2']]; },
    revisa(v) { const d = v.di + 2 * hol(v), p = (v.D - d) / 2, L = []; if (p <= 0) L.push({ n: 'error', t: 'El agujero (' + f(d, 2) + ' mm) es igual o mayor que el exterior: no queda pieza.' }); else if (p < 0.8) L.push({ n: 'error', t: 'La pared mide ' + f(p, 2) + ' mm: menos de 0,8 (dos líneas de tu boquilla). No se puede imprimir bien.' }); else if (p < 1.2) L.push({ n: 'aviso', t: 'Pared de ' + f(p, 2) + ' mm: se imprime, pero es frágil.' }); if (v.valona && v.Dv <= v.D) L.push({ n: 'error', t: 'La valona tiene que ser más ancha que el casquillo.' }); return L.length ? L : [{ n: 'ok', t: 'Sin problemas.' }]; },
    construye(v) { const d = v.di + 2 * hol(v), ch = Math.min(v.chaflan || 0, (v.D - d) / 4, v.L / 4); let m = N.forma3d('tubo', { d: v.D, interior: d, h: v.L });
      if (ch > 0.05) { const C = N.CSX(), cono = (r0, r1, h) => N.MF().cylinder(h, r0, r1, Math.max(48, Math.round(v.D * 4 / 4) * 4)); m = m.subtract(cono(d / 2 + ch, d / 2, ch).translate([0, 0, -0.001])).subtract(cono(d / 2, d / 2 + ch, ch).translate([0, 0, v.L - ch + 0.001])); void C; }
      if (v.valona) m = m.add(N.forma3d('tubo', { d: v.Dv, interior: d, h: v.ev })); return { partes: [{ m, nombre: 'casquillo' }] }; },
    cotas(v) { return [{ a: [-v.D / 2, -v.D / 2 - 4, v.L], b: [v.D / 2, -v.D / 2 - 4, v.L], t: 'Ø ' + f(v.D, 2) }, { a: [-v.di / 2, 0, v.L + 2], b: [v.di / 2, 0, v.L + 2], t: 'Ø ' + f(v.di, 2) + ' eje' }, { a: [v.D / 2 + 4, 0, 0], b: [v.D / 2 + 4, 0, v.L], t: f(v.L, 2) }]; },
    kit(v) { return { t: 'Prueba: un anillo de 3 mm del casquillo', d: 'Mételo en el eje: con «a presión» debe entrar con fuerza; con «gira», girar sin bailar.', partes: [{ m: this.construye(Object.assign({}, v, { L: Math.min(3, v.L), valona: false })).partes[0].m, nombre: 'casquillo_prueba' }] }; } },

  eje: { e: '📍', t: 'Eje / pasador', d: 'Cilindro con plano en D opcional',
    campos: [n('D', 'Diámetro', { req: 1, min: 0.8, max: 300 }), n('L', 'Largo', { req: 1, min: 1, max: 600 }), c('planoD', 'Con plano (eje en D)', { def: false }), n('plano', 'Del plano al otro lado', { req: 1, min: 0.3, max: 300, si: v => v.planoD }), n('chaflan', 'Chaflán en las puntas', { def: 0.4, est: 1, min: 0, max: 5 }), s('ajuste', 'Va en un agujero de…', [['nominal', 'Su misma medida (lo ajusto yo)'], ['menos', 'Restar mi holgura «encaja» (' + f(ENCAJES.justo) + ' por lado)']], { def: 'nominal', est: 1, ayuda: 'Si mides el AGUJERO donde va, resta tu holgura para que entre.' })],
    ejemplo: { D: 5, L: 30 },
    dd(v) { return v.D - (v.ajuste === 'menos' ? 2 * ENCAJES.justo : 0); },
    calcula(v) { return [['Diámetro que se imprime', f(this.dd(v), 3) + ' mm', v.ajuste === 'menos' ? 'diámetro − 2 × holgura «encaja»' : 'el que has puesto'], ['Consejo', 'Imprímelo TUMBADO', 'de pie se parte por las capas']]; },
    revisa(v) { const L = []; if (v.planoD && v.plano >= v.D) L.push({ n: 'error', t: 'La medida del plano tiene que ser menor que el diámetro.' }); if (v.D < 3) L.push({ n: 'aviso', t: 'Un eje de menos de 3 mm impreso es frágil: mejor uno de acero.' }); if (v.L / v.D > 15) L.push({ n: 'aviso', t: 'Muy largo y fino: se doblará. Imprímelo tumbado y en PETG o nailon.' }); return L.length ? L : [{ n: 'ok', t: 'Sin problemas.' }]; },
    construye(v) { const d = this.dd(v), ch = Math.min(v.chaflan || 0, d / 4); let m = N.forma3d('cilindro', { d, h: v.L }); if (ch > 0.05) { const cono = (r0, r1, h) => N.MF().cylinder(h, r0, r1, Math.max(32, Math.round(d * 4 / 4) * 4)); const ani = N.forma3d('tubo', { d: d + 2, interior: d - 2 * ch, h: ch }); void ani; m = m.intersect(cono(d / 2 - ch, d / 2 - ch + v.L, v.L).translate([0, 0, 0])).intersect(cono(d / 2 - ch + v.L, d / 2 - ch, v.L)); }
      if (v.planoD && v.plano < d) m = m.subtract(N.forma3d('caja', { x: d, y: d, z: v.L + 2, radio: 0 }).translate([v.plano - d / 2 + d / 2, 0, -1])); return { partes: [{ m, nombre: 'eje' }] }; },
    cotas(v) { return [{ a: [-v.D / 2, -v.D / 2 - 3, v.L], b: [v.D / 2, -v.D / 2 - 3, v.L], t: 'Ø ' + f(this.dd(v), 2) }, { a: [v.D / 2 + 4, 0, 0], b: [v.D / 2 + 4, 0, v.L], t: f(v.L, 2) }]; },
    kit(v) { return { t: 'Prueba: 8 mm del eje', d: 'Pruébalo en su agujero antes de imprimirlo entero.', partes: [{ m: this.construye(Object.assign({}, v, { L: Math.min(8, v.L) })).partes[0].m, nombre: 'eje_prueba' }] }; } },

  placa: { e: '▭', t: 'Placa con agujeros', d: 'Soporte plano, agujeros a distancia exacta',
    campos: [n('L', 'Largo', { req: 1, min: 2, max: 600 }), n('W', 'Ancho', { req: 1, min: 2, max: 600 }), n('e', 'Grosor', { req: 1, min: 0.6, max: 100 }), n('na', 'Agujeros en fila', { req: 1, u: '', min: 0, max: 50, paso: 1 }), n('dh', 'Diámetro de los agujeros', { req: 1, min: 0.5, max: 200, si: v => v.na > 0, ayuda: 'Mide el TORNILLO o el eje; el agujero se hará con tu holgura «encaja».' }), n('dc', 'Distancia entre centros', { req: 1, min: 0.5, max: 600, si: v => v.na > 1, ayuda: 'De centro a centro de dos agujeros seguidos (mide de borde izquierdo a borde izquierdo: es lo mismo).' }), n('filas', 'Filas', { def: 1, u: '', min: 1, max: 20, paso: 1 }), n('df', 'Distancia entre filas', { req: 1, min: 0.5, max: 600, si: v => v.filas > 1 }), n('radio', 'Redondeo de las esquinas', { def: 2, est: 1, min: 0, max: 100 }), c('avellanado', 'Agujeros avellanados (tornillo de cabeza plana)', { def: false })],
    ejemplo: { L: 60, W: 20, e: 4, na: 2, dh: 4, dc: 40 },
    pos(v) { const P = [], n0 = Math.max(0, Math.round(v.na)), fl = Math.max(1, Math.round(v.filas || 1)); for (let j = 0; j < fl; j++) for (let i = 0; i < n0; i++) P.push([(i - (n0 - 1) / 2) * (v.dc || 0), (j - (fl - 1) / 2) * (v.df || 0)]); return P; },
    calcula(v) { const d = v.dh + 2 * ENCAJES.justo, P = this.pos(v), mx = P.length ? Math.max(...P.map(p => Math.abs(p[0]))) : 0, my = P.length ? Math.max(...P.map(p => Math.abs(p[1]))) : 0; return [['Agujero que se imprime', f(d, 3) + ' mm', 'tornillo + 2 × holgura «encaja»'], ['Del borde al primer centro (largo)', f(v.L / 2 - mx, 2) + ' mm', ''], ['Del borde al centro (ancho)', f(v.W / 2 - my, 2) + ' mm', '']]; },
    revisa(v) { const d = v.dh + 2 * ENCAJES.justo, P = this.pos(v), L = []; if (P.length) { const mx = Math.max(...P.map(p => Math.abs(p[0]))), my = Math.max(...P.map(p => Math.abs(p[1]))), bx = v.L / 2 - mx - d / 2, by = v.W / 2 - my - d / 2; if (bx < 0 || by < 0) L.push({ n: 'error', t: 'Los agujeros se salen de la placa: necesita al menos ' + f(2 * mx + d + 2, 1) + ' × ' + f(2 * my + d + 2, 1) + ' mm.' }); else if (Math.min(bx, by) < 1) L.push({ n: 'aviso', t: 'Del agujero al borde quedan ' + f(Math.min(bx, by), 2) + ' mm: se puede romper al apretar el tornillo (mejor 2 mm o más).' }); if (v.na > 1 && v.dc - d < 1) L.push({ n: 'error', t: 'Los agujeros se tocan entre sí: la distancia entre centros tiene que ser mayor que ' + f(d + 1, 2) + ' mm.' }); } return L.length ? L : [{ n: 'ok', t: 'Sin problemas.' }]; },
    construye(v) { let m = N.forma3d('caja', { x: v.L, y: v.W, z: v.e, radio: Math.min(v.radio || 0, v.L / 2 - 0.1, v.W / 2 - 0.1) }); const d = v.dh + 2 * ENCAJES.justo, A = this.pos(v).map(([x, y]) => { let a = N.forma3d('cilindro', { d, h: v.e + 2 }).translate([x, y, -1]); if (v.avellanado) a = a.add(N.MF().cylinder(d * 0.6, d / 2, d, Math.max(32, Math.round(d * 4)), false).translate([x, y, v.e - d * 0.6 + 0.01])); return a; }); if (A.length) m = m.subtract(N.union(A)); return { partes: [{ m, nombre: 'placa' }] }; },
    cotas(v) { const P = this.pos(v), L = [{ a: [-v.L / 2, -v.W / 2 - 4, v.e], b: [v.L / 2, -v.W / 2 - 4, v.e], t: f(v.L, 2) }]; if (P.length > 1 && v.na > 1) L.push({ a: [P[0][0], P[0][1], v.e + 3], b: [P[1][0], P[1][1], v.e + 3], t: f(v.dc, 2) + ' entre centros' }); return L; },
    kit(v) { return { t: 'Plantilla de 1,2 mm con los agujeros', d: 'Ponla sobre el aparato: si los tornillos pasan por los agujeros, las distancias están bien.', partes: [{ m: this.construye(Object.assign({}, v, { e: 1.2, avellanado: false })).partes[0].m, nombre: 'plantilla_agujeros' }] }; } },

  escuadra: { e: '📐', t: 'Escuadra', d: 'Soporte en L con agujeros',
    campos: [n('A', 'Brazo de abajo (largo)', { req: 1, min: 4, max: 400 }), n('B', 'Brazo de arriba (alto)', { req: 1, min: 4, max: 400 }), n('W', 'Ancho', { req: 1, min: 3, max: 400 }), n('e', 'Grosor', { req: 1, min: 1, max: 50 }), n('dh', 'Diámetro de los tornillos', { req: 1, min: 0, max: 50, ayuda: '0 = sin agujeros.' }), n('dbo', 'Del rincón al centro del agujero', { req: 1, min: 1, max: 400, si: v => v.dh > 0, ayuda: 'La misma en los dos brazos.' }), c('nervio', 'Con nervio de refuerzo', { def: true })],
    ejemplo: { A: 30, B: 30, W: 20, e: 4, dh: 4, dbo: 18 },
    calcula(v) { return [['Agujero que se imprime', f(v.dh + 2 * ENCAJES.justo, 3) + ' mm', 'tornillo + 2 × holgura «encaja»'], ['Consejo', 'Imprímela tumbada de lado', 'las capas no se separan al cargarla']]; },
    revisa(v) { const L = [], d = v.dh + 2 * ENCAJES.justo; if (v.dh > 0) { if (v.dbo - d / 2 < v.e) L.push({ n: 'error', t: 'El agujero choca con el otro brazo: el centro tiene que estar a más de ' + f(v.e + d / 2, 2) + ' mm del rincón.' }); if (v.dbo + d / 2 > Math.min(v.A, v.B) - 1) L.push({ n: 'error', t: 'El agujero se sale del brazo: el centro tiene que estar a menos de ' + f(Math.min(v.A, v.B) - 1 - d / 2, 2) + ' mm.' }); if (d > v.W - 2) L.push({ n: 'error', t: 'El agujero es más ancho que la escuadra.' }); } return L.length ? L : [{ n: 'ok', t: 'Sin problemas.' }]; },
    construye(v) { const caja = (x, y, z) => N.forma3d('caja', { x, y, z, radio: 0 }); let m = caja(v.A, v.W, v.e).translate([v.A / 2, 0, 0]).add(caja(v.e, v.W, v.B).translate([v.e / 2, 0, 0]));
      if (v.nervio) { const t = Math.min(v.A, v.B) * 0.45, C = N.cs([[[v.e, 0], [v.e + t, 0], [v.e, t]]], 'Positive'); m = m.add(C.extrude(Math.min(3, v.W / 4)).rotate([90, 0, 0]).translate([0, Math.min(3, v.W / 4) / 2, v.e])); }
      if (v.dh > 0) { const d = v.dh + 2 * ENCAJES.justo; m = m.subtract(N.forma3d('cilindro', { d, h: v.e + 2 }).translate([v.dbo, 0, -1])).subtract(N.forma3d('cilindro', { d, h: v.e + 2 }).rotate([0, 90, 0]).translate([-1, 0, v.dbo])); }
      return { partes: [{ m, nombre: 'escuadra' }] }; },
    cotas(v) { return [{ a: [0, -v.W / 2 - 4, 0], b: [v.A, -v.W / 2 - 4, 0], t: f(v.A, 2) }, { a: [-4, -v.W / 2 - 4, 0], b: [-4, -v.W / 2 - 4, v.B], t: f(v.B, 2) }]; },
    kit(v) { return { t: 'Prueba: la escuadra con 1,5 mm de grosor', d: 'Para comprobar que los agujeros caen donde deben antes de imprimirla gruesa.', partes: [{ m: this.construye(Object.assign({}, v, { e: 1.5, nervio: false })).partes[0].m, nombre: 'escuadra_prueba' }] }; } }
};
// ---------- 🏎️ DIFERENCIAL RC COMPLETO (con montaje virtual) ----------
const est = (k, t, def, o = {}) => n(k, t, Object.assign({ def, est: 1 }, o));
const OPS_ROD = Object.keys(RODAMIENTOS).map(k => [k, k.replace(/x/g, ' × ') + ' mm']);
let memoDif = null; // (lo calcula una vez por cambio: revisar, calcular y construir usan el mismo resultado)
const difDe = v => { const key = JSON.stringify(v); if (!memoDif || memoDif.key !== key || !memoDif.vivo) memoDif = { key, vivo: true, R: diferencial(Object.assign({}, v, { ns: Number(v.ns), alfa: Number(v.alfa) })) }; return memoDif.R; };
export const olvidaDif = () => { if (memoDif) memoDif.vivo = false; };
TIPOS.diferencialRC = { e: '🏎️', t: 'Diferencial RC completo', d: 'Carcasa con corona, tapa, satélites, piñón y caja',
  campos: [
    est('m', 'Módulo de la corona y el piñón', 1, { min: 0.5, max: 3, paso: 0.05, ayuda: 'Habitual en RC 1/10 entre 0,8 y 1. Si cambias un piñón de tu coche, mídelo: exterior ÷ (dientes + 2) aproximado (en cónicos el exterior se mide en el talón).' }),
    est('zc', 'Dientes de la corona', 38, { u: '', min: 20, max: 80, paso: 1 }), est('zpi', 'Dientes del piñón de ataque', 13, { u: '', min: 8, max: 30, paso: 1 }),
    s('alfa', 'Ángulo de presión', [['20', '20°'], ['25', '25°']], { def: '20', est: 1 }), est('juego', 'Juego entre dientes', 0.1, { min: 0, max: 0.4, paso: 0.01 }),
    est('ms', 'Módulo de planetarios y satélites', 0.8, { min: 0.5, max: 2, paso: 0.05 }), est('zpl', 'Dientes de cada planetario', 16, { u: '', min: 10, max: 30, paso: 1 }), est('zsa', 'Dientes de cada satélite', 10, { u: '', min: 8, max: 20, paso: 1 }),
    s('ns', 'Satélites', [['2', '2 satélites'], ['4', '4 satélites (más fuerte)']], { def: '2' }),
    s('salida', 'Salida de los planetarios', [['hex', 'Hexágono'], ['d', 'Eje en D'], ['redonda', 'Redonda']], { def: 'hex', est: 1 }), est('ejeSal', 'Medida de la salida (entre caras / diámetro)', 5, { min: 2, max: 12 }),
    est('cruceta', 'Pasador de la cruceta (Ø)', 3, { min: 1.5, max: 6, paso: 0.1, ayuda: 'Mejor un pasador de ACERO (o un tornillo) de esa medida: impreso es débil.' }),
    s('rodCaja', 'Rodamientos de la carcasa', OPS_ROD, { def: '10x15x4', est: 1, ayuda: 'Tamaños normalizados (interior × exterior × ancho). Elige los que vayas a comprar o los que lleva tu coche.' }),
    s('rodPinon', 'Rodamientos del piñón', OPS_ROD, { def: '5x11x4', est: 1 }), est('ejePinon', 'Eje del piñón (Ø)', 5, { min: 2, max: 10, paso: 0.5 }),
    s('torTapa', 'Tornillos de la tapa', Object.keys(TORNILLOS).map(k => [k, k]), { def: 'M2.5', est: 1 }), s('torCaja', 'Tornillos de la caja', Object.keys(TORNILLOS).map(k => [k, k]), { def: 'M3', est: 1 }),
    est('pared', 'Grosor de las paredes', 2.5, { min: 1.6, max: 5, paso: 0.1 }), est('holg', 'Holgura de lo que gira con la caja', 1.5, { min: 0.6, max: 4, paso: 0.1 }),
    s('vista', 'Ver', [['montado', 'Montado (la caja, transparente)'], ['corte', 'En corte (por la mitad)'], ['despiezado', 'Despiezado']], { def: 'montado' })],
  ejemplo: {},
  calcula(v) { const R = difDe(v), C = R.cuentas; return [['Relación (corona ÷ piñón)', f(C.relacion, 3) + ' : 1', 'vueltas del motor por vuelta de rueda (antes de la reductora)'], ['Ángulos de los conos', f(C.delta1, 2) + '° · ' + f(C.delta2, 2) + '°', 'tan δ₁ = z₁ ÷ z₂ ; δ₂ = 90° − δ₁'], ['Radios primitivos', f(C.r1, 2) + ' · ' + f(C.r2, 2) + ' mm', 'módulo × dientes ÷ 2'], ['Distancia del vértice al talón', f(C.Rc, 3) + ' mm', 'r₂ ÷ sen δ₂'], ['Talón de la corona (desde el eje del piñón)', f(C.H2, 3) + ' mm', '= r₁ (r ÷ tan δ)'], ['Talón del piñón (desde el eje de las ruedas)', f(C.H1, 3) + ' mm', '= r₂'], ['Ancho del diente', f(C.b, 2) + ' mm', '≈ distancia al talón ÷ 3'], ['Planetarios / satélites', f(C.deltaPl, 1) + '° / ' + f(C.deltaSa, 1) + '°', 'sus conos'], ['Hueco interior de la carcasa', 'Ø ' + f(2 * C.Rin, 2) + ' mm', 'medido sobre las piezas'], ['Lo más ancho que gira', 'Ø ' + f(2 * C.Rrot, 2) + ' mm', 'con su holgura']]; },
  revisa(v) { const R = difDe(v); return R.avisos.concat(R.choques.filter(c => c.vol > 0.05).length ? [] : []); },
  construye(v) { const R = difDe(v), P = R.partes, vista = v.vista || 'montado', desp = vista === 'despiezado';
    const mov = (m, d) => desp ? m.translate(d) : m, corte = m => vista === 'corte' ? m.intersect(N.forma3d('caja', { x: 600, y: 600, z: 300, radio: 0 }).translate([0, 0, -300])) : m;
    const vis = [[P.carcasa, '#e2231a', 'carcasa', [0, 0, 0]], [P.tapa, '#ff8a3d', 'tapa', [-22, 0, 0]], [P.planD, '#2457d6', 'planetario', [30, 0, 0]], [P.planI, '#2457d6', 'planetario', [-40, 0, 0]], ...P.sats.map((m, i) => [m, '#29d3ff', 'satélite', [0, 0, 0].map((x, k) => k === 2 ? (i % 2 ? -1 : 1) * 30 : 0)]), [P.pasador, '#b8bec4', 'cruceta', [0, 0, 45]], [P.pinon, '#7c6cff', 'piñón', [0, -18, 0]], [P.eje, '#b8bec4', 'eje', [0, -32, 0]]];
    const partes = vis.map(([m, color, nombre, d]) => ({ m: corte(mov(m, d)), color, nombre })), caja = [[P.cajaAbajo, [0, 0, -40]], [P.cajaArriba, [0, 0, 60]]];
    const fantasma = desp ? caja.map(([m, d]) => ({ m: m.translate(d), color: '#8e9196', nombre: 'caja' })) : [{ m: corte(P.cajaAbajo), color: '#8e9196', nombre: 'caja' }];
    if (vista !== 'corte' && !desp) fantasma.push({ m: P.cajaArriba, color: '#8e9196', nombre: 'caja' });
    return { partes, fantasma, choques: R.choques, lista: R.lista, imprimir: R.piezasImprimir.map(([t, m, c]) => ({ m, nombre: t, color: c })) }; },
  cotas(v) { const R = difDe(v), C = R.cuentas; return [{ a: [-C.Rrot, -C.Rrot - 4, 0], b: [C.Rrot, -C.Rrot - 4, 0].map((x, i) => i === 0 ? C.Rrot : x), t: 'Ø ' + f(2 * C.Rrot, 1) + ' (gira)' }, { a: [C.H2, 3, 0], b: [0, 3, 0], t: f(C.H2, 2) + ' = r₁' }, { a: [-3, -C.H1, 0], b: [-3, 0, 0], t: f(C.H1, 2) + ' = r₂' }]; },
  kit(v) { const R = difDe(v), RC = RODAMIENTOS[v.rodCaja] || RODAMIENTOS['10x15x4'], RP = RODAMIENTOS[v.rodPinon] || RODAMIENTOS['5x11x4'], pres = ENCAJES.presion;
    const placa = N.forma3d('caja', { x: RC[1] + RP[1] + 16, y: Math.max(RC[1], RP[1]) + 8, z: Math.max(RC[2], RP[2]) + 1.5, radio: 2 });
    let m = placa.subtract(N.forma3d('cilindro', { d: RC[1] + 2 * pres, h: RC[2] + 1 }).translate([-(RP[1] + 6) / 2, 0, 1.5])).subtract(N.forma3d('cilindro', { d: RP[1] + 2 * pres, h: RP[2] + 1 }).translate([(RC[1] + 6) / 2, 0, 1.5]));
    const buje = N.forma3d('cilindro', { d: RC[0] - 2 * pres, h: RC[2] + 2 }).translate([0, Math.max(RC[1], RP[1]) / 2 + 10, 0]);
    return { t: 'Prueba de rodamientos (alojamientos ' + v.rodCaja + ' y ' + v.rodPinon + ' + buje) y la pareja corona–piñón', d: 'Mete los rodamientos: deben entrar a presión (tu holgura 0,05). Gira el piñón contra la corona a mano: deben rodar sin saltar ni bloquearse. Si algo no encaja, cambia la holgura o el juego antes de imprimir la caja.', partes: [{ m: m.add(buje), nombre: 'prueba_rodamientos' }, { m: R.partes.pinon.translate([0, 0, 0]), nombre: 'piñon' }, { m: R.partes.carcasa, nombre: 'carcasa_con_corona' }] }; } };

export const DATOS_APARATO = DATOS;

// ---------- valores de partida y estados ----------
// estado de cada medida: 'tuya' (la has escrito o confirmado) · 'estimada' (valor de partida: confírmalo) · 'falta'
export function nuevo(tipo) {
  const T = TIPOS[tipo], v = {}, est = {};
  T.campos.forEach(c => { if (c.def !== undefined) { v[c.k] = c.tipo === 'num' ? Number(c.def) : c.def; est[c.k] = c.est ? 'estimada' : 'tuya'; } else if (c.tipo === 'chk') { v[c.k] = false; est[c.k] = 'tuya'; } else if (c.tipo === 'sel') { v[c.k] = c.ops[0][0]; est[c.k] = 'tuya'; } else { v[c.k] = c.tipo === 'num' ? null : ''; est[c.k] = c.req ? 'falta' : 'tuya'; } });
  DATOS.forEach(c => { v[c.k] = ''; });
  return { tipo, v, est };
}
export const visibles = (tipo, v) => TIPOS[tipo].campos.filter(c => !c.si || c.si(v));
export function faltan(tipo, v) { return visibles(tipo, v).filter(c => c.req && (v[c.k] == null || v[c.k] === '' || !isFinite(Number(v[c.k])) || (c.tipo === 'num' && Number(v[c.k]) <= 0 && c.min > 0))).map(c => c.t); }
// valores listos para construir (números de verdad; lo opcional vacío = 0)
export function valores(tipo, v) { const o = Object.assign({}, v); TIPOS[tipo].campos.forEach(c => { if (c.tipo === 'num') o[c.k] = v[c.k] == null || v[c.k] === '' ? 0 : Number(v[c.k]); }); return o; }
